DROP TABLE IF EXISTS t_wps;
CREATE TABLE t_wps
(
  c_id CHAR(36) NOT NULL COMMENT '主键',
  c_key VARCHAR(255) DEFAULT NULL COMMENT '饮用KEY',
  c_name VARCHAR(255) DEFAULT NULL COMMENT '名称',
  c_appId VARCHAR(255) DEFAULT NULL COMMENT 'APP ID',
  c_secret VARCHAR(255) DEFAULT NULL COMMENT '密钥',
  c_watermark VARCHAR(255) DEFAULT NULL COMMENT '水印',
  c_nick VARCHAR(255) DEFAULT NULL COMMENT '默认昵称',
  c_avatar VARCHAR(255) DEFAULT NULL COMMENT '默认头像',

  PRIMARY KEY pk(c_id) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
